### ISSUE TITLE
Liquid Support

### ISSUE THREAD

**Issue by DO-Jordan** [theJian/gulp-shopify-sass#23]
Hello. Are they're currently any plans for Shopify's Liquid inside your SASS imports? 
Ex: 
     .test {
          color: {{ settings.button-color.id }};
     }

**Comment by theJian** [comment]
This plugin does one simple thing. It looks for the `import` operator and concats them by the order. You can use it with other plugins together to suit your needs.

**Comment by dankiv** [comment]
@DO-Jordan you can use this tutorial
https://gist.github.com/stewartknapman/8346708
